# Generated by Django 5.0.4 on 2024-04-06 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todousers_remove_teacher_user_delete_userdata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todousers',
            name='password',
        ),
        migrations.AddField(
            model_name='todousers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todousers',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='todousers',
            name='todo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todousers',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
