# Generated by Django 5.0.4 on 2024-04-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_todousers_password_todousers_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todousers',
            old_name='date_created',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='todousers',
            name='date_edited',
        ),
    ]
